version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./docker-configs:/dockerconfigs:ro
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  nginx:
    external: true